import { CoffeeProps } from "./pages/Home/components/CoffeeCard";

export const coffeeList: CoffeeProps[] = [
  {
    id: "1",
    name: "Expresso Tradicional",
    imgUrl: "/src/assets/expresso-tradicional.svg",
    tags: ["tradicional"],
    description: "O tradicional café feito com água quente e grãos moídos",
    price: 9.9,
  },
  {
    id: "2",
    name: "Expresso Americano",
    imgUrl: "/src/assets/expresso-americano.svg",
    tags: ["tradicional"],
    description: "Expresso diluído, menos intenso que o tradicional",
    price: 9.9,
  },
  {
    id: "3",
    name: "Expresso Cremoso",
    imgUrl: "/src/assets/expresso-cremoso.svg",
    tags: ["tradicional"],
    description: "Café expresso tradicional com espuma cremosa",
    price: 9.9,
  },
  {
    id: "4",
    name: "Expresso Gelado",
    imgUrl: "/src/assets/expresso-gelado.svg",
    tags: ["tradicional", "gelado"],
    description: "Bebida preparada com café expresso e cubos de gelo",
    price: 9.9,
  },
  {
    id: "5",
    name: "Café com Leite",
    imgUrl: "/src/assets/cafe-com-leite.svg",
    tags: ["tradicional", "com leite"],
    description: "Meio a meio de expresso tradicional com leite vaporizado",
    price: 9.9,
  },
  {
    id: "6",
    name: "Latte",
    imgUrl: "/src/assets/latte.svg",
    tags: ["tradicional", "com leite"],
    description:
      "Uma dose de café expresso com o dobro de leite e espuma cremosa",
    price: 9.9,
  },
  {
    id: "7",
    name: "Capuccino",
    imgUrl: "/src/assets/capuccino.svg",
    tags: ["tradicional", "com leite"],
    description:
      "Bebida com canela feita de doses iguais de café, leite e espuma",
    price: 9.9,
  },
  {
    id: "8",
    name: "Macchiato",
    imgUrl: "/src/assets/macchiato.svg",
    tags: ["tradicional", "com leite"],
    description:
      "Café expresso misturado com um pouco de leite quente e espuma",
    price: 9.9,
  },
  {
    id: "9",
    name: "Mocaccino",
    imgUrl: "/src/assets/mocaccino.svg",
    tags: ["tradicional", "com leite"],
    description: "Café expresso com calda de chocolate, pouco leite e espuma",
    price: 9.9,
  },
  {
    id: "10",
    name: "Chocolate Quente",
    imgUrl: "/src/assets/chocolate-quente.svg",
    tags: ["especial", "com leite"],
    description: "Bebida feita com chocolate dissolvido no leite quente e café",
    price: 9.9,
  },
  {
    id: "11",
    name: "Cubano",
    imgUrl: "/src/assets/cubano.svg",
    tags: ["especial", "alcoólico", "gelado"],
    description:
      "Drink gelado de café expresso com rum, creme de leite e hortelã",
    price: 9.9,
  },
  {
    id: "12",
    name: "Havaiano",
    imgUrl: "/src/assets/havaiano.svg",
    tags: ["especial"],
    description: "Bebida adocicada preparada com café e leite de coco",
    price: 9.9,
  },
  {
    id: "13",
    name: "Árabe",
    imgUrl: "/src/assets/arabe.svg",
    tags: ["especial"],
    description: "Bebida preparada com grãos de café árabe e especiarias",
    price: 9.9,
  },
  {
    id: "14",
    name: "Irlandês",
    imgUrl: "/src/assets/irlandes.svg",
    tags: ["especial", "alcoolico"],
    description: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
    price: 9.9,
  },
];
